Refactor requests window
Oneirocom/Magick pull request #1022
Opened 2023-06-12 18:09 UTC by Emmyn5600

## What Changed:

I refactored the request table by add the `TableComponent` reusable component to display all requests available 

## How to test:

if you  already have some request data , the go to the requests window , if not create a new discord spell and then interact with is in the chat window by sending few requests and the go back to the request window to view all the requests you have sent . there you can even delete a request by click on action.

## Additional information:
![Screenshot from 2023-06-12 20-01-13](https://github.com/Oneirocom/Magick/assets/55635977/669f048d-6c0a-4445-aec7-5978d51a9ca4)
![Screenshot from 2023-06-12 20-01-20](https://github.com/Oneirocom/Magick/assets/55635977/b556b26e-0b8f-4ba5-a3ad-d95f68bd846e)

2023-06-12 19:48 UTC, Knar33 submitted a review, later dismissed
Seems to work for me. it's a bit ugly when looking at embeddings though, not sure a good way to fix it just figured I'd point it out:
![image](https://github.com/Oneirocom/Magick/assets/4692561/d7bb798c-5fea-48e5-a572-3aa325430a82)

2023-06-13 06:39 UTC, FabriceIRANKUNDA commented
> Seems to work for me. it's a bit ugly when looking at embeddings though, not sure a good way to fix it just figured I'd point it out: ![image](https://user-images.githubusercontent.com/4692561/245253046-d7bb798c-5fea-48e5-a572-3aa325430a82.png)

I think in this case we need to collapse the embeddings and show them up when expanded, @Emmyn5600 you can view the Figma design and use the collapse to handle this case.

2023-06-13 06:59 UTC, FabriceIRANKUNDA approved these changes

2023-06-15 19:22 UTC, coffeeorgreentea approved these changes

2023-06-20 07:06 UTC, FabriceIRANKUNDA requested changes
- Delete many still does not work for me, look at the screenshot below in the console there is a feathers' error
- Also when I selected a row and delete it using the delete option on the menu, the selected row state should be cleared because if it stays and I press the delete selected button a request to delete a row which has been already deleted can be triggered to an error!

<img width="1439" alt="Screenshot 2023-06-20 at 08 56 47" src="https://github.com/Oneirocom/Magick/assets/58092199/0443d95f-7eae-4b9b-b253-7ff646b49463">

2023-06-20 07:50 UTC, FabriceIRANKUNDA approved these changes

2023-06-20 07:51 UTC, FabriceIRANKUNDA commented
> * Delete many still does not work for me, look at the screenshot below in the console there is a feathers' error
> * Also when I selected a row and delete it using the delete option on the menu, the selected row state should be cleared because if it stays and I press the delete selected button a request to delete a row which has been already deleted can be triggered to an error!
> 
> <img alt="Screenshot 2023-06-20 at 08 56 47" width="1439" src="https://user-images.githubusercontent.com/58092199/247031803-0443d95f-7eae-4b9b-b253-7ff646b49463.png">

LGTM! npm run dev fixed it!

2023-06-20 14:12 UTC, merged