OMI_Personality
Oneirocom/Magick pull request #793
Opened 2023-05-05 18:22 UTC by ultrabot2022

## What Changed:
SXP component has been changed with OMI_Personality extension.

## How to test:
Drag/Drop VRM files to see the agent

2023-05-05 20:49 UTC, fire commented
There are some errors in ESLint. Are you able to resolve?

2023-05-05 22:11 UTC, Knar33 commented
This is injecting the same personality into every VRM that gets uploaded? Seems like we'd want to grab the data out of them dynamically.

2023-05-05 23:39 UTC, ultrabot2022 commented
> This is injecting the same personality into every VRM that gets uploaded? Seems like we'd want to grab the data out of them dynamically.

Yes, it is injecting OMI_Personality but they are not same. The Agent is related with node id.

2023-05-05 23:41 UTC, ultrabot2022 commented
> There are some errors in ESLint. Are you able to resolve?

I just come back here. I will be busy but I will fix it soon.

2023-05-09 16:53 UTC, fire requested changes

2023-05-09 16:53 UTC, fire commented on plugins/avatar/client/src/components/Chat/ChatBox.tsx
> +    // stopSpeech()
Remove unused code that is commented.

2023-05-09 16:53 UTC, fire commented on plugins/avatar/client/src/components/Chat/ChatBox.tsx
> +    //mic button on/off
Remove unused code that is commented.

2023-05-09 16:53 UTC, fire commented on plugins/avatar/client/src/components/Scene/XrTest.css
> +
Add a new line.

2023-05-09 16:53 UTC, fire commented on plugins/avatar/client/src/hooks/useOMIPersonality.ts
> +}
Add a new line.

2023-05-09 16:54 UTC, fire commented on plugins/avatar/client/src/components/Sxp/Sxp.jsx
> +              // const omiPersonality = node.userData.gltfExtensions.OMI_personality;
Why is this code commented?

1. If used please implement
2. Else delete.

2023-05-09 16:54 UTC, fire commented on plugins/avatar/client/src/hooks/useVrmMixamoAnimations.ts
> +      // customDebug().log('useVrmMixamoAnimations#useEffect: vrmBoneNode: ', vrmBoneNode)
If used please complete, else delete the comment.

2023-05-09 16:55 UTC, fire commented on plugins/avatar/client/src/components/Scene/Scene.jsx
> +        {/* <axesHelper args={[AXIS_LEN]} /> */}
Why is this code commented?

2023-05-09 16:55 UTC, fire commented on plugins/avatar/client/src/App.module.css
> +}
Missing new line at the end of the file.

2023-05-09 16:59 UTC, fire commented
VR testing is not requested for now.

2023-05-09 16:59 UTC, fire commented
What is the state of LookingGlass support? Do you want it to be tested?

2023-05-12 00:40 UTC, closed without merging